"""
bootstrap_requirements.py — fallback used by setup.sh when no root requirements.txt exists.

Consolidates unique package specs from all tools/*/requirements.txt files,
appends setup CLI deps, and writes requirements.txt at repo root.

Run standalone: python tools/setup/bootstrap_requirements.py
"""
from __future__ import annotations

import pathlib
import re

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
TOOLS_DIR = REPO_ROOT / "tools"
OUTPUT = REPO_ROOT / "requirements.txt"

SETUP_DEPS = [
    "click>=8.1.0",
    "questionary>=2.0.0",
    "ruamel.yaml>=0.18.0",
]

HEADER = """\
# Root requirements — covers all tools and the setup CLI.
# Install once with: pip install -r requirements.txt
# Auto-generated by tools/setup/bootstrap_requirements.py
"""


def _parse_reqs(path: pathlib.Path) -> list[str]:
    lines = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            lines.append(line)
    return lines


def _pkg_name(spec: str) -> str:
    """Extract bare package name from a requirement spec."""
    return re.split(r"[>=<!;\s\[]", spec)[0].lower().replace("-", "_")


def consolidate() -> None:
    seen: dict[str, str] = {}  # normalised name → raw spec

    # Collect from all tools
    for req_file in sorted(TOOLS_DIR.rglob("requirements.txt")):
        for spec in _parse_reqs(req_file):
            name = _pkg_name(spec)
            if name not in seen:
                seen[name] = spec

    # Add setup-specific deps
    for spec in SETUP_DEPS:
        name = _pkg_name(spec)
        if name not in seen:
            seen[name] = spec

    lines = [HEADER] + [v for v in seen.values()] + [""]
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"[bootstrap] wrote {OUTPUT}")


if __name__ == "__main__":
    consolidate()
